### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sjlagasse** [danjmoore598/prj-rev-bwfs-dasmoto#6]
### Criteria 1: HTML and CSS Linking  
* _Score Level: 4/4
* _Comment(s): Great job linking. Everything was imported correctly.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level: 4/4
* _Comment(s): Your webpage looks great. I like the centering of the page.
 
### Criteria 3: HTML Elements and Content
* _Score Level: 4/4
* _Comment(s): Your HTML was great. Nice use of elements, wrapping divs and indentation.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level: 3/4
* _Comment(s): Your CSS looked really good overall. You had all the right styles. Make sure to only set your `font-family` once.
 
### Overall Score: 15/16

Your project was really good! Your webpage looked awesome and I like that you added extra styles to center the page. Just be careful when you go to your Tea Cozy project as they will want that exactly to the mock, no extras. Your HTML was wonderful and you CSS was almost perfect. Great job on this one and keep up the good work!

**Comment by danjmoore598** [comment]
Wow, thanks for getting that reviewed so quickly! And I really appreciate the feedback.
